root: true
env:
  es2021: true
  node: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2021
  sourceType: module
plugins:
  - "@typescript-eslint"
extends:
  - "plugin:@typescript-eslint/recommended"
  - "htmlacademy/node"
  - "plugin:import/errors"
  - "plugin:import/warnings"
rules:
  import/first: "error"
  import/newline-after-import:
    - "error"
    - { "count": 1 }
  import/order:
    - "error"
    - groups:
        - ["external", "internal"]
      newlines-between: "always"
      alphabetize: { order: 'asc', caseInsensitive: true }
  import/no-unresolved: "off"
